### ISSUE TITLE
Error installing on Mac 

### ISSUE THREAD

**Issue by ba3lwi** [bhklab/wCI#10]
I get an error during compilation of fastRCI.c file. Please see below:

>install_github("bhklab/wCI")
Downloading GitHub repo bhklab/wCI@HEAD
'/usr/bin/git' clone --depth 1 --no-hardlinks --recurse-submodules https://github.com/bhklab/wCI-libraries.git /var/folders/tl/lsvhkqyx7zx6rr89q_ws0ybc0000gp/T//RtmpwP7gE6/remotes3557ca4423c/bhklab-wCI-5b4f5b8/src
Cloning into '/var/folders/tl/lsvhkqyx7zx6rr89q_ws0ybc0000gp/T//RtmpwP7gE6/remotes3557ca4423c/bhklab-wCI-5b4f5b8/src'...
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?
1: All                         
2: CRAN packages only          
3: None                        
4: Rcpp (1.0.7 -> 1.0.8) [CRAN]
Enter one or more numbers, or an empty line to skip updates: 
✓  checking for file ‘/private/var/folders/tl/lsvhkqyx7zx6rr89q_ws0ybc0000gp/T/RtmpwP7gE6/remotes3557ca4423c/bhklab-wCI-5b4f5b8/DESCRIPTION’ ...
─  preparing ‘wCI’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘wCI_0.1.0.tar.gz’
Installing package into ‘/Users/wail/.RLibrary’
(as ‘lib’ is unspecified)
installing *source* package ‘wCI’ ...
using staged installation
libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c CI_functions.cpp -o CI_functions.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c CI_functions_new.c -o CI_functions_new.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c fastCI.c -o fastCI.o
fastCI.c:223:30: warning: unused variable 'callMethods' [-Wunused-const-variable]
static const R_CallMethodDef callMethods[]  = {
                             ^
1 warning generated.
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.0/Resources/library/Rcpp/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c fastRCI.c -o fastRCI.o
fastRCI.c:148:5: error: implicit declaration of function 'merge_sort' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    merge_sort(oleft_obs, oleft_preds, oleft_disc, oleft_pairs, left_length, 
    ^
fastRCI.c:154:5: error: implicit declaration of function 'merge_two_sides' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    merge_two_sides(left_obs, left_preds, left_disc, left_pairs, left_length,
    ^
fastRCI.c:154:5: note: did you mean 'rmerge_two_sides'?
fastRCI.c:13:6: note: 'rmerge_two_sides' declared here
void rmerge_two_sides(double *left_obs, double *left_preds, double *left_disc, double *left_pairs, int left_length,
     ^
fastRCI.c:201:3: error: implicit declaration of function 'merge_sort' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
  merge_sort(in_obs, in_preds, in_disc, in_pairs, N, 
  ^
3 errors generated.
make: *** [fastRCI.o] Error 1
ERROR: compilation failed for package ‘wCI’
removing ‘/Users/wail/.RLibrary/wCI’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/tl/lsvhkqyx7zx6rr89q_ws0ybc0000gp/T//RtmpwP7gE6/file3553f8b112/wCI_0.1.0.tar.gz’ had non-zero exit status

**Comment by ChristopherEeles** [comment]
Hi @ba3lwi,

It compiles successfully in Ubuntu 20.04 running via Windows Subsystem for Linux (WSL).

Since the error is thrown by `clang++` I suspect it may be a macOS specific bug. I will need to get access to an Apple machine to reproduce.

Based on [this](https://stackoverflow.com/questions/55896653/gcc-how-to-stop-false-positive-warning-implicit-function-declaration-for-functio) I think it is probably just a missing forward function declarations for the three functions which error.

Apparently you can't ignore implicit function declaration errors in C++, only in C: https://stackoverflow.com/questions/11816133/disable-function-declaration-error-in-avr-g

@p-smirnov can you try compiling and see if you can replicate it?

Best,
Christopher Eeles
Software Developer
BHK Lab | PM-Research | UHN

**Comment by ba3lwi** [comment]
Thanks for the reply @ChristopherEeles . I solved this for now by using GNU gcc on my mac machine. It seems from looking at the compilation message that both g++ and clang++ were used when this worked out!

**Comment by p-smirnov** [comment]
@ba3lwi It seems like -Werror is now turned on by default on a Mac. 

Either way, this was caused by a spelling mistake in a file that doesn't work anyways. I fixed the spelling mistake, but will eventually just remove the broken file since Farnoosh's code implements it correctly in a different file.

**Comment by ChristopherEeles** [comment]
This seems resolved, feel free to reopen if it is not.

Best,
Chris
